### ISSUE TITLE
45 to 50 CPU msec usage on resmon

### ISSUE THREAD

**Issue by KetoPz** [majestic-development/majestic-deathscreen#1]
What is this???
![Screenshot 2024-02-29 170018](https://github.com/majestic-development/majestic-deathscreen/assets/108960934/0d62745e-2364-4737-a159-476bd9f1a6a8)

**Comment by majestic-development** [comment]
ill work on a fix in the next upcoming days, i dont know why, it doesnt do that for me but il check it out

**Comment by KetoPz** [comment]
i did fixed it, it was a weird loop, i can send it

**Comment by majestic-development** [comment]
yeah, i havent had much time to fix it, you can send if you wish.

**Comment by DoubleDxx** [comment]
> i did fixed it, it was a weird loop, i can send it

how to fix it?

**Comment by majestic-development** [comment]
ill send out a update shortly, or contact me in a ticket in our discord.

**Comment by eysikun** [comment]
any update?

**Comment by KetoPz** [comment]
sorry for the late response, this is the fix, is only for client.lua:



local isDead = false

RegisterNetEvent('majestic-deathscreen:openUI', function(time)
    isDead = true
    SendNUIMessage({action = "DSMenu", open = true, time = time})
    if Config.Blur then
        TriggerScreenblurFadeIn()
    end
    handleControls(false)
    disableSounds()
end)

RegisterNetEvent('majestic-deathscreen:revive', function()
    isDead = false
    SendNUIMessage({action = "DSMenu", open = false})
    if Config.Blur then
        TriggerScreenblurFadeOut()
    end
    enableSounds()
end)

RegisterNetEvent('majestic-deathscreen:die', function(time)
    isDead = true
    SendNUIMessage({action = "DSMenu", open = true, time = time})
    if Config.Blur then
        TriggerScreenblurFadeIn()
    end
    handleControls(false)
    disableSounds()
end)

RegisterNetEvent('majestic-deathscreen:res', function()
    SendNUIMessage({action = "res"})
end)

RegisterNetEvent('majestic-deathscreen:updateRes', function(time)
    SendNUIMessage({action = "updateRes", time = time})
end)

RegisterCommand('test',function()
    TriggerEvent('majestic-deathscreen:updateRes', 0)
end)

function handleControls(disable)
    DisableAllControlActions(0)
    if Config.Controls.Mouse then
        EnableControlAction(0, 1, not disable)
        EnableControlAction(0, 2, not disable)
    end
    for k, v in pairs(Config.Controls.Enable) do
        EnableControlAction(0, v, not disable)
    end
end

function toggleSounds(enable)
    if enable then
        StopAudioScene("DLC_MPHEIST_TRANSITION_TO_APT_FADE_IN_RADIO_SCENE")
        SetStaticEmitterEnabled("LOS_SANTOS_VANILLA_UNICORN_01_STAGE", true)
        -- Resto de habilitación de sonidos...
    else
        StartAudioScene("DLC_MPHEIST_TRANSITION_TO_APT_FADE_IN_RADIO_SCENE")
        SetStaticEmitterEnabled("LOS_SANTOS_VANILLA_UNICORN_01_STAGE", false)
        -- Resto de deshabilitación de sonidos...
    end
end

function disableSounds()
    toggleSounds(false)
    SetScenarioTypeEnabled("WORLD_VEHICLE_STREETRACE", false)
    -- Puedes agregar más deshabilitaciones aquí...
end

function enableSounds()
    toggleSounds(true)
    SetScenarioTypeEnabled("WORLD_VEHICLE_STREETRACE", true)
    -- Puedes agregar más habilitaciones aquí...
end
